"""Prepare a serving instance's storage, without ever raising at import.

Three facts about Azure App Service shape this module, and each of them broke a
deployment before it was written down:

  * `/home` is the only path that survives a restart, and it is an SMB mount.
    SQLite's WAL needs shared memory that SMB does not provide, so a database
    opened in WAL mode there fails on first write.
  * A container that exits is restarted, and fifteen restarts exhaust a Free
    plan's quota — which then disables Kudu, hiding the logs that would explain
    the original failure. A crash loop destroys its own evidence.
  * Therefore nothing here may raise. A serving process that cannot open its
    database should start, say so, and keep answering: a readable 503 is worth
    more than an invisible restart loop.

The pipeline is unaffected: it runs locally against a local file, in WAL, with
none of this in the path.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import os
import shutil
import sqlite3
from pathlib import Path

#: Content the deployment ships, and the column that says how current a row is.
#:
#: An earlier version of this comment claimed the UI never writes these. That was
#: simply false — `POST /api/topics/{id}/description|brief|market-size|competition`
#: all write them, and the shipped UI has a Regenerate button wired to each. So a
#: deployment that replaced them unconditionally would silently discard work a
#: curator paid a model call for. Every row is therefore compared on its own
#: timestamp and the newer one wins, which makes the package authoritative for
#: content it actually refreshed and production authoritative for everything it
#: regenerated since.
#:
#: `opportunity_spaces` carries no timestamp and is written only by the pipeline
#: (`scoring.py`, `pipeline/`), never by the API, so it is taken wholesale. It has
#: to travel with the content: its `version` column is what `brief_for_topic`
#: compares against, so freezing it while shipping new briefs would flag every one
#: of them "the topic has been refreshed since".
CONTENT_TABLES: tuple[tuple[str, str | None], ...] = (
    ("opportunity_spaces", None),
    ("topic_descriptions", "generated_at"),
    ("topic_briefs", "generated_at"),
    ("topic_competition", "computed_at"),
    ("market_sizes", "computed_at"),
)

#: Set when preparation failed, and reported by /healthz instead of crashing.
STARTUP_ERROR: str | None = None
STARTUP_NOTES: list[str] = []


def _note(message: str) -> None:
    stamped = f"{dt.datetime.now(dt.timezone.utc):%H:%M:%S} bootstrap: {message}"
    STARTUP_NOTES.append(stamped)
    try:
        print(stamped, flush=True)
    except OSError:
        pass  # a closed or full stdout must not be able to kill the container
    log_path = os.getenv("RADAR_STARTUP_LOG")
    if log_path:
        try:
            Path(log_path).parent.mkdir(parents=True, exist_ok=True)
            with open(log_path, "a", encoding="utf-8") as handle:
                handle.write(stamped + "\n")
        except OSError:
            pass  # the log is a courtesy; failing to write one must not matter


def _digest(path: Path) -> str:
    """A content fingerprint, so the sync runs on a new package and not on every
    cold start — the container restarts far more often than it is deployed."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def _columns(conn: sqlite3.Connection, schema: str, table: str) -> list[tuple[str, str, int]]:
    """(name, declared type, primary-key position) for each column."""
    return [(row[1], (row[2] or "").upper(), row[5])
            for row in conn.execute(f'PRAGMA {schema}.table_info("{table}")')]


def _sync_content(db_path: Path, seed: Path) -> bool:
    """Bring the persistent database's shipped content up to the package.

    The database is seeded once and then never replaced, so that a deployment
    cannot discard what production accumulated. That is right for feedback and
    workflow state and wrong for content: descriptions and briefs generated by
    the batch job would ship as files nobody could reach, because the rows that
    make them visible stayed at whatever the first deployment seeded. Sixty-two
    briefs sat on disk that way, and the UI reported none existed.

    Only CONTENT_TABLES move, and a row moves only when the package's copy is
    newer than the one already stored — see the note on CONTENT_TABLES for why
    that comparison is not optional. Rows are matched on the topic, so content
    the package does not carry is left alone rather than deleted.

    Returns True when every table was applied, which is what allows the marker to
    be written; a partial sync must be retried on the next start rather than
    recorded as done.
    """
    conn = None
    try:
        conn = sqlite3.connect(db_path, timeout=60)
        # Load-bearing, not incidental: INSERT OR REPLACE is a DELETE followed by
        # an INSERT, and these tables are the parents of workflow_state and
        # feedback via ON DELETE CASCADE. With foreign keys enforced, refreshing a
        # topic would cascade production's own rows out from under it.
        conn.execute("PRAGMA foreign_keys = OFF")
        conn.execute("ATTACH DATABASE ? AS pkg", (str(seed),))
        applied, complete = [], True
        for table, stamp in CONTENT_TABLES:
            live, packaged = _columns(conn, "main", table), _columns(conn, "pkg", table)
            if not live or not packaged:
                # Schema drift between the package and the stored database. Say so
                # and refuse to record the sync as done, so it is retried rather
                # than suppressed for the life of this package.
                _note(f"content sync: {table} missing from "
                      f"{'the package' if not packaged else 'the stored database'} — skipped")
                complete = False
                continue
            shared = [name for name, _, _ in live if name in {n for n, _, _ in packaged}]
            keys = [name for name, _, pk in live if pk]
            types = {name: kind for name, kind, _ in live}
            # A single INTEGER `id` alongside an opportunity_id is a surrogate key:
            # the value is minted per database and means nothing across the two.
            # A TEXT `id` — opportunity_spaces — is the topic itself, and matches.
            surrogate = (keys == ["id"] and types.get("id", "").startswith("INT")
                         and "opportunity_id" in types)
            names = ", ".join(f'"{c}"' for c in shared)
            fresher = (f"AND m.\"{stamp}\" > p.\"{stamp}\"" if stamp else "AND 0")
            before = conn.total_changes  # cumulative on the connection, so take a delta
            if not surrogate and keys:
                match = " AND ".join(f'm."{k}" = p."{k}"' for k in keys)
                conn.execute(
                    f"INSERT OR REPLACE INTO main.{table} ({names}) "
                    f"SELECT {names} FROM pkg.{table} AS p "
                    f"WHERE NOT EXISTS (SELECT 1 FROM main.{table} AS m "
                    f"                   WHERE {match} {fresher})")
            elif surrogate:
                # A surrogate key: ids are minted per database and mean nothing
                # across the two, so replace a topic's rows as a set. Only topics
                # the package has refreshed are touched; one regenerated in
                # production keeps every row it computed, including methods the
                # package does not carry.
                body = [c for c in shared if c != "id"]
                names = ", ".join(f'"{c}"' for c in body)
                if stamp:
                    conn.execute(
                        f"DELETE FROM main.{table} WHERE opportunity_id IN ("
                        f"  SELECT p.opportunity_id FROM pkg.{table} AS p GROUP BY p.opportunity_id"
                        f"   HAVING MAX(p.\"{stamp}\") >= COALESCE("
                        f"     (SELECT MAX(m.\"{stamp}\") FROM main.{table} AS m"
                        f"       WHERE m.opportunity_id = p.opportunity_id), ''))")
                else:
                    conn.execute(f"DELETE FROM main.{table} WHERE opportunity_id IN "
                                 f"(SELECT DISTINCT opportunity_id FROM pkg.{table})")
                conn.execute(
                    f"INSERT INTO main.{table} ({names}) SELECT {names} FROM pkg.{table} AS p "
                    f"WHERE NOT EXISTS (SELECT 1 FROM main.{table} AS m "
                    f"                   WHERE m.opportunity_id = p.opportunity_id)")
            else:
                _note(f"content sync: {table} has no key this can match on — skipped")
                complete = False
                continue
            applied.append(f"{table}={conn.total_changes - before}")
        conn.commit()
        _note("content sync: " + (", ".join(applied) if applied else "nothing to apply"))
        return complete
    except Exception as exc:  # noqa: BLE001 — stale content beats a dead container
        _note(f"content sync FAILED ({type(exc).__name__}: {exc}) — serving what is already stored")
        return False
    finally:
        if conn is not None:
            try:
                conn.close()
            except Exception:  # noqa: BLE001
                pass


def _sync_briefs(db_path: Path, packaged: Path, served: Path) -> None:
    """Put the PDF each stored brief row describes where the API will find it.

    Driven by the rows rather than the directory, because `content_hash` is the
    SHA-256 of the PDF the row was written for. That makes the row the authority:
    if it names the packaged file, the packaged file belongs on disk; if it names
    something else, production regenerated this brief and its PDF must not be
    overwritten — which an earlier unconditional copy did, on every container
    start, leaving the row describing bytes that were no longer there.
    """
    conn = None
    try:
        conn = sqlite3.connect(db_path, timeout=60)
        rows = conn.execute("SELECT filename, content_hash FROM topic_briefs").fetchall()
    except Exception as exc:  # noqa: BLE001
        _note(f"briefs: cannot read the brief rows ({type(exc).__name__}: {exc})")
        return
    finally:
        if conn is not None:
            try:
                conn.close()
            except Exception:  # noqa: BLE001
                pass

    new = updated = kept = 0
    for filename, content_hash in rows:
        source, target = packaged / filename, served / filename
        if not source.is_file():
            continue
        try:
            if not target.exists():
                shutil.copy(source, target)
                new += 1
            elif _digest(target) == content_hash:
                continue                       # already the file the row describes
            elif _digest(source) == content_hash:
                shutil.copy(source, target)    # the row names the packaged PDF
                updated += 1
            else:
                kept += 1                      # regenerated in production — leave it
        except OSError as exc:
            _note(f"briefs: {filename} could not be placed ({exc})")
    if new or updated or kept:
        _note(f"briefs: {new} new, {updated} updated, {kept} kept as production wrote them")


def prepare(db_path: Path, package_root: Path) -> None:
    """Seed the persistent database, make its journal mode usable, ship content.

    Seeding happens once: a deployment must not discard the feedback, assessments
    and workflow decisions production accumulated. Content is separate and does
    move forward — see _sync_content.
    """
    global STARTUP_ERROR
    try:
        db_path.parent.mkdir(parents=True, exist_ok=True)
        briefs = os.getenv("RADAR_BRIEF_DIR")
        if briefs:
            Path(briefs).mkdir(parents=True, exist_ok=True)

        seed = package_root / "data" / "radar.db"
        if not db_path.exists() and seed.exists():
            _note(f"seeding {db_path} from {seed} ({seed.stat().st_size / 1048576:.0f} MB)")
            # Through a temporary name: an interrupted copy would otherwise leave
            # a truncated file that looks seeded, and seeding never runs twice.
            staged = db_path.with_name(db_path.name + ".partial")
            shutil.copy(seed, staged)
            os.replace(staged, db_path)
            _note("seed complete")

        # Before any other write. /home is SMB, where WAL does not work, and a
        # freshly seeded file carries whatever mode it was built with.
        if db_path.exists():
            mode = os.getenv("RADAR_SQLITE_JOURNAL_MODE", "WAL").upper()
            connection = sqlite3.connect(db_path, timeout=30)
            try:
                before = connection.execute("PRAGMA journal_mode").fetchone()[0]
                after = connection.execute(f"PRAGMA journal_mode = {mode}").fetchone()[0]
                _note(f"journal mode {before} -> {after}")
            finally:
                connection.close()
        else:
            _note(f"no database at {db_path} — the API will report this rather than crash")
            return

        if not seed.exists() or db_path.resolve() == seed.resolve():
            # In a checkout the served database IS the packaged one, so there is
            # nothing to bring forward and ATTACH would alias the file to itself.
            return

        marker = db_path.parent / ".content-fingerprint"
        try:
            fingerprint = _digest(seed)
            current = marker.read_text().strip() if marker.is_file() else None
        except OSError as exc:
            _note(f"content sync: cannot fingerprint the package ({exc}) — skipping")
            return
        if current == fingerprint:
            return  # the container cold starts far more often than it is deployed

        complete = _sync_content(db_path, seed)
        packaged_briefs = package_root / "data" / "briefs"
        if briefs and packaged_briefs.is_dir():
            _sync_briefs(db_path, packaged_briefs, Path(briefs))
        if complete:
            try:
                marker.write_text(fingerprint)
            except OSError:
                pass  # re-syncing next start is wasteful, not wrong
    except Exception as exc:  # noqa: BLE001 — see the module docstring
        STARTUP_ERROR = f"{type(exc).__name__}: {exc}"
        _note(f"FAILED: {STARTUP_ERROR}")
