"""Sales and presales brief as a PDF (FR-18).

FR-18 was listed in the README as deliberately not built, with the note that
"the read API exposes everything an exporter needs". This is that exporter.

The brief is assembled, not written. Three kinds of content meet on the page and
they are kept visibly distinct, because a reader has to know which is which:

  computed    scores, market sizes, competitive intensity, portfolio distance.
              Produced by `scoring`, `sizing` and `competition`, reproducible
              from stored inputs (DR-05), never generated by a model.
  curated     named Orange assets, references, certifications, competitors —
              from the business graph and the competitor register (DR-11).
  written     the narrative sections and the solution diagram, generated under
              the §4.4.4 defences and stripped where they failed them.

Every figure on the page therefore has a provenance, and the last page says so:
the weight set that produced the scores, the sizing version that produced the
money, the competitor register version, and the prompt and model that wrote the
prose (DR-10, NFR-02). A brief that cannot be traced is a brochure.

reportlab is used rather than an HTML-to-PDF pipeline: it has no browser
dependency, which matters for a sovereign deployment (NFR-05), and the solution
diagram is drawn with exact geometry rather than hoped-for CSS.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import logging
import os
import re
import unicodedata
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (BaseDocTemplate, Flowable, Frame, KeepTogether, ListFlowable,
                                ListItem, PageBreak, PageTemplate, Paragraph, Spacer, Table,
                                TableStyle)

from .competition import competition_for_topic
from .competitor_analysis import analysis_for_topic
from .config import Config
from .db import Database
from .pipeline.describe import description_for_topic
from .readmodel import ReadModel
from .sizing import format_eur, sizes_for_topic

log = logging.getLogger(__name__)

#: The set of sections a current brief contains. Bumped when a section is added,
#: so a brief rendered before that section exists is detectable as INCOMPLETE
#: rather than merely old. A stale brief and an incomplete brief are different
#: problems: the first was right when it was made, the second never carried the
#: section at all, and the interface says which.
BRIEF_SCHEMA = "brief-2-competitor-analysis"

# Orange Business brand-adjacent palette. Orange is reserved for Orange's own
# components and for emphasis, exactly as in the UI, so the reader learns one
# meaning for it rather than two.
ORANGE = colors.HexColor("#F16E00")
ORANGE_DARK = colors.HexColor("#C24E00")
INK = colors.HexColor("#141414")
MUTED = colors.HexColor("#666666")
RULE = colors.HexColor("#DDDDDD")
SURFACE = colors.HexColor("#F6F6F6")
WARN = colors.HexColor("#8A5A00")
WARN_BG = colors.HexColor("#FFF6E5")

PROVIDER_STYLE = {
    "orange": (ORANGE, colors.white, ORANGE_DARK),
    "partner": (colors.HexColor("#F9D3AE"), INK, ORANGE),
    "customer": (colors.white, INK, colors.HexColor("#9A9A9A")),
    "third_party": (colors.HexColor("#EFEFEF"), INK, colors.HexColor("#C4C4C4")),
}
PROVIDER_LABEL = {
    "orange": "Orange asset",
    "partner": "Partner",
    "customer": "Customer-owned",
    "third_party": "Third party / to be sourced",
}

COMPETITION_COLOUR = {
    "none": colors.HexColor("#7A7A7A"),
    "low": colors.HexColor("#2E7D32"),
    "medium": colors.HexColor("#B26A00"),
    "high": colors.HexColor("#B3261E"),
}


# ---------------------------------------------------------------------------
# Solution diagram
# ---------------------------------------------------------------------------


class SolutionDiagram(Flowable):
    """Layered solution schematic drawn from the validated diagram spec.

    The model supplies structure (layers, boxes, providers, flows); this draws
    it. Keeping the geometry here rather than in the prompt is what makes the
    picture legible every time: boxes are sized to the layer, labels wrap at a
    measured width, and arrows are computed from real box positions instead of
    being guessed by a model that cannot see its own output.
    """

    def __init__(self, diagram: dict[str, Any], width: float):
        super().__init__()
        self.diagram = diagram
        self.width = width
        self.layers = diagram.get("layers") or []
        self.flows = diagram.get("flows") or []
        self.layer_height = 24 * mm
        self.gap = 7 * mm
        self.height = len(self.layers) * self.layer_height + max(0, len(self.layers) - 1) * self.gap

    # -- geometry ----------------------------------------------------------

    def _boxes(self) -> dict[str, tuple[float, float, float, float]]:
        """Node label -> (x, y, w, h), in flowable coordinates."""
        boxes: dict[str, tuple[float, float, float, float]] = {}
        label_column = 26 * mm
        usable = self.width - label_column - 2 * mm
        for index, layer in enumerate(self.layers):
            # Layers are listed top-down; reportlab's origin is bottom-left.
            top = self.height - index * (self.layer_height + self.gap)
            nodes = layer.get("nodes") or []
            if not nodes:
                continue
            spacing = 4 * mm
            box_width = (usable - spacing * (len(nodes) - 1)) / len(nodes)
            box_height = 15 * mm
            y = top - self.layer_height + (self.layer_height - box_height) / 2
            for position, node in enumerate(nodes):
                x = label_column + position * (box_width + spacing)
                boxes[node["label"]] = (x, y, box_width, box_height)
        return boxes

    def draw(self) -> None:
        canvas = self.canv
        boxes = self._boxes()

        for index, layer in enumerate(self.layers):
            top = self.height - index * (self.layer_height + self.gap)
            canvas.setFillColor(SURFACE)
            canvas.setStrokeColor(RULE)
            canvas.setLineWidth(0.4)
            canvas.roundRect(0, top - self.layer_height, self.width, self.layer_height, 3, stroke=1, fill=1)

            canvas.setFillColor(MUTED)
            canvas.setFont("Helvetica-Bold", 6.5)
            for line_no, line in enumerate(_wrap(layer.get("label", ""), 16)[:3]):
                canvas.drawString(3 * mm, top - 8 * mm - line_no * 7, line.upper())

            for node in layer.get("nodes") or []:
                x, y, width, height = boxes[node["label"]]
                fill, text_colour, border = PROVIDER_STYLE.get(
                    node.get("provider", "third_party"), PROVIDER_STYLE["third_party"]
                )
                canvas.setFillColor(fill)
                canvas.setStrokeColor(border)
                canvas.setLineWidth(0.9)
                canvas.roundRect(x, y, width, height, 2.5, stroke=1, fill=1)

                canvas.setFillColor(text_colour)
                canvas.setFont("Helvetica-Bold", 7.2)
                # Characters that fit at 7.2pt in this box, less a small margin.
                per_line = max(8, int((width - 4 * mm) / 3.7))
                lines = _wrap(node["label"], per_line)[:3]
                start = y + height / 2 + (len(lines) - 1) * 4.4 - 2.6
                for line_no, line in enumerate(lines):
                    canvas.drawCentredString(x + width / 2, start - line_no * 8.8, line)

        self._draw_flows(boxes)

    def _draw_flows(self, boxes: dict[str, tuple[float, float, float, float]]) -> None:
        canvas = self.canv
        canvas.setLineWidth(0.8)
        for flow in self.flows:
            source = boxes.get(flow["from"])
            target = boxes.get(flow["to"])
            if not source or not target:
                continue
            sx, sy, sw, sh = source
            tx, ty, tw, th = target
            start_x, end_x = sx + sw / 2, tx + tw / 2
            if abs(sy - ty) < 1:
                continue  # same layer: an arrow would only add noise
            going_up = ty > sy
            start_y = sy + sh if going_up else sy
            end_y = ty if going_up else ty + th

            canvas.setStrokeColor(ORANGE)
            canvas.setFillColor(ORANGE)
            canvas.line(start_x, start_y, end_x, end_y)
            self._arrowhead(end_x, end_y, start_x, start_y)

            label = (flow.get("label") or "").strip()
            if label and abs(start_y - end_y) > 12:
                text = label[:24]
                canvas.setFont("Helvetica", 5.4)
                width = canvas.stringWidth(text, "Helvetica", 5.4)
                mid_x, mid_y = (start_x + end_x) / 2, (start_y + end_y) / 2
                # The arrow passes through the label, so the label gets a solid
                # backdrop rather than being drawn on top of a line.
                canvas.setFillColor(colors.white)
                canvas.rect(mid_x - width / 2 - 1.5, mid_y - 2.4, width + 3, 7, stroke=0, fill=1)
                canvas.setFillColor(MUTED)
                canvas.drawCentredString(mid_x, mid_y, text)

    def _arrowhead(self, x: float, y: float, from_x: float, from_y: float) -> None:
        import math

        angle = math.atan2(y - from_y, x - from_x)
        size = 3.2
        path = self.canv.beginPath()
        path.moveTo(x, y)
        path.lineTo(x - size * math.cos(angle - 0.4), y - size * math.sin(angle - 0.4))
        path.lineTo(x - size * math.cos(angle + 0.4), y - size * math.sin(angle + 0.4))
        path.close()
        self.canv.drawPath(path, stroke=0, fill=1)


def _wrap(text: str, per_line: int) -> list[str]:
    words, lines, current = text.split(), [], ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) <= per_line:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines or [text]


# ---------------------------------------------------------------------------
# Document
# ---------------------------------------------------------------------------


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", parent=base["Title"], fontName="Helvetica-Bold",
                                fontSize=17, leading=21, textColor=INK, alignment=TA_LEFT,
                                spaceAfter=2),
        "kicker": ParagraphStyle("kicker", parent=base["Normal"], fontName="Helvetica-Bold",
                                 fontSize=7.6, leading=10, textColor=ORANGE_DARK, spaceAfter=4),
        "h2": ParagraphStyle("h2", parent=base["Heading2"], fontName="Helvetica-Bold",
                             fontSize=11, leading=14, textColor=INK, spaceBefore=11, spaceAfter=4),
        "h3": ParagraphStyle("h3", parent=base["Heading3"], fontName="Helvetica-Bold",
                             fontSize=8.6, leading=11, textColor=MUTED, spaceBefore=7, spaceAfter=2),
        "body": ParagraphStyle("body", parent=base["Normal"], fontName="Helvetica",
                               fontSize=9.1, leading=12.6, textColor=INK, spaceAfter=5),
        "small": ParagraphStyle("small", parent=base["Normal"], fontName="Helvetica",
                                fontSize=7.6, leading=10, textColor=MUTED, spaceAfter=3),
        "cite": ParagraphStyle("cite", parent=base["Normal"], fontName="Courier",
                               fontSize=6.6, leading=9, textColor=MUTED, spaceAfter=6),
        "cell": ParagraphStyle("cell", parent=base["Normal"], fontName="Helvetica",
                               fontSize=7.6, leading=9.6, textColor=INK),
        "cellhead": ParagraphStyle("cellhead", parent=base["Normal"], fontName="Helvetica-Bold",
                                   fontSize=7.4, leading=9.4, textColor=colors.white),
        "warn": ParagraphStyle("warn", parent=base["Normal"], fontName="Helvetica",
                               fontSize=7.8, leading=10.4, textColor=WARN,
                               backColor=WARN_BG, borderPadding=5, spaceAfter=6),
    }


class BriefBuilder:
    """Assembles one opportunity brief and renders it to a PDF file."""

    def __init__(self, cfg: Config, db: Database, output_dir: Path | None = None):
        self.cfg = cfg
        self.db = db
        self.read = ReadModel(cfg, db)
        self.styles = _styles()
        self.output_dir = Path(
            output_dir or os.getenv("RADAR_BRIEF_DIR")
            or (Path(cfg.db_path).parent / "briefs")
        )

    # ------------------------------------------------------------------

    def build(self, topic_id: str) -> dict[str, Any]:
        topic = self.read.topic(topic_id)
        if topic is None:
            raise KeyError(f"No such topic: {topic_id}")
        description = description_for_topic(self.db, topic_id)
        competition = competition_for_topic(self.db, topic_id)
        sizes = sizes_for_topic(self.db, topic_id)
        analysis = analysis_for_topic(self.db, topic_id)

        self.output_dir.mkdir(parents=True, exist_ok=True)
        filename = f"{topic_id}-opportunity-brief.pdf"
        path = self.output_dir / filename
        story = self._story(topic, description, competition, sizes, analysis)
        self._render(path, story, topic)

        payload = path.read_bytes()
        digest = hashlib.sha256(payload).hexdigest()
        now = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
        with self.db.cursor() as cur:
            cur.execute(
                """INSERT INTO topic_briefs
                       (opportunity_id, generated_at, topic_version, path, filename, bytes,
                        content_hash, description_at, market_size_at, weight_set, sizing_version,
                        prompt_version, model_version, pipeline_version, brief_schema)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                   ON CONFLICT(opportunity_id) DO UPDATE SET
                       generated_at=excluded.generated_at, topic_version=excluded.topic_version,
                       path=excluded.path, filename=excluded.filename, bytes=excluded.bytes,
                       content_hash=excluded.content_hash, description_at=excluded.description_at,
                       market_size_at=excluded.market_size_at, weight_set=excluded.weight_set,
                       sizing_version=excluded.sizing_version, prompt_version=excluded.prompt_version,
                       model_version=excluded.model_version, pipeline_version=excluded.pipeline_version,
                       brief_schema=excluded.brief_schema""",
                (topic_id, now, topic["version"], str(path), filename, len(payload), digest,
                 (description or {}).get("generated_at"),
                 sizes[0]["computed_at"] if sizes else None,
                 topic.get("provenance", {}).get("weight_set") or self.cfg.weight_set,
                 sizes[0]["sizing_version"] if sizes else self.cfg.sizing_version,
                 (description or {}).get("provenance", {}).get("prompt_version"),
                 (description or {}).get("provenance", {}).get("model_version"),
                 self.cfg.pipeline_version, BRIEF_SCHEMA),
            )
        log.info("Brief for %s: %s (%d bytes)", topic_id, path, len(payload))
        return brief_for_topic(self.db, topic_id) or {}

    # -- rendering ---------------------------------------------------------

    def _render(self, path: Path, story: list[Any], topic: dict[str, Any]) -> None:
        doc = BaseDocTemplate(
            str(path), pagesize=A4,
            leftMargin=17 * mm, rightMargin=17 * mm, topMargin=17 * mm, bottomMargin=16 * mm,
            title=f"{topic['id']} — {topic['statement'][:90]}",
            author="Orange Business Innovation Radar",
            subject="Opportunity space brief for sales and presales",
        )
        frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="body")
        statement = topic["statement"]
        weight_set = topic.get("provenance", {}).get("weight_set") or self.cfg.weight_set

        def decorate(canvas, document):
            canvas.saveState()
            canvas.setFillColor(ORANGE)
            canvas.rect(0, A4[1] - 6, A4[0], 6, stroke=0, fill=1)
            canvas.setFont("Helvetica", 6.6)
            canvas.setFillColor(MUTED)
            canvas.drawString(17 * mm, 10 * mm,
                              f"Orange Business Innovation Radar · {topic['id']} · "
                              f"{_clip(statement, 74)}")
            canvas.drawRightString(A4[0] - 17 * mm, 10 * mm, f"page {document.page}")
            canvas.setStrokeColor(RULE)
            canvas.setLineWidth(0.4)
            canvas.line(17 * mm, 13 * mm, A4[0] - 17 * mm, 13 * mm)
            if document.page > 1:
                canvas.setFont("Helvetica", 6.6)
                canvas.drawString(17 * mm, A4[1] - 12 * mm,
                                  f"Internal — evidence-bound opportunity brief · weight set {weight_set}")
            canvas.restoreState()

        doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=decorate)])
        doc.build(story)

    # -- story -------------------------------------------------------------

    def _story(self, topic: dict[str, Any], description: dict[str, Any] | None,
               competition: dict[str, Any] | None, sizes: list[dict[str, Any]],
               analysis: dict[str, Any] | None = None) -> list[Any]:
        style = self.styles
        story: list[Any] = []
        story += self._cover(topic, competition, sizes)

        if description and description.get("stale"):
            story.append(Paragraph(
                "This brief was written against an earlier version of the topic. The evidence has "
                "moved since; regenerate before using it with a customer.", style["warn"]))
        if topic.get("evidence_gap_warning"):
            density = topic.get("reference_density") or {}
            story.append(Paragraph(
                f"<b>Evidence gap (SC-13).</b> Orange has "
                f"{density.get('published_story_count', 0)} published reference(s) in "
                f"{_text(topic['labels']['vertical'])}, below the threshold of "
                f"{density.get('threshold', '?')}. A customer conversation here has no proof point "
                f"behind it yet.", style["warn"]))

        sections = (description or {}).get("sections", {})
        titles = (description or {}).get("section_titles", {})

        if "summary" in sections:
            story.append(Paragraph("The opportunity", style["h2"]))
            story.append(Paragraph(_text(sections["summary"]["text"]), style["body"]))
        elif not description:
            story.append(Paragraph(
                "No generated description yet — this brief carries the computed and curated content "
                "only. Generate one from the radar to add the narrative sections.", style["warn"]))

        story += self._market_size(sizes)
        story += self._diagram(description)

        for name in ("what_is_changing", "who_buys_and_why"):
            if name in sections:
                story.append(Paragraph(titles.get(name, name), style["h2"]))
                story.append(Paragraph(_text(sections[name]["text"]), style["body"]))
                story += self._citation_line(sections[name].get("signals"), topic)

        story += self._why_hot(topic)
        story += self._delivery(topic, sections, titles)
        story += self._competition(competition, sections, titles, topic)
        story += self._competitor_analysis(analysis)
        story += self._questions_and_objections(description)
        story += self._actions(topic, sections, titles)
        story += self._evidence_appendix(topic)
        story += self._method(topic, description, competition, sizes)
        return story

    # -- blocks ------------------------------------------------------------

    def _cover(self, topic: dict[str, Any], competition: dict[str, Any] | None,
               sizes: list[dict[str, Any]]) -> list[Any]:
        style = self.styles
        labels = topic["labels"]
        best = _preferred_size(sizes)
        attractiveness = (topic.get("attractiveness") or {}).get("score")
        right_to_win = (topic.get("right_to_win") or {}).get("score")

        header = [
            Paragraph("OPPORTUNITY BRIEF · SALES AND PRESALES", style["kicker"]),
            Paragraph(_text(topic["statement"]), style["title"]),
            Paragraph(
                f"{_text(labels['vertical'])} &nbsp;×&nbsp; {_text(labels['use_case'])} "
                f"&nbsp;×&nbsp; {_text(labels['technology'])} &nbsp;·&nbsp; {topic['id']} "
                f"v{topic['version']} &nbsp;·&nbsp; refreshed {topic['last_refresh']}",
                style["small"]),
            Spacer(1, 4),
        ]

        rows = [[
            Paragraph("ATTRACTIVENESS", style["cellhead"]),
            Paragraph("RIGHT TO WIN", style["cellhead"]),
            Paragraph("COMPETITION", style["cellhead"]),
            Paragraph("SERVICEABLE MARKET", style["cellhead"]),
            Paragraph("HORIZON", style["cellhead"]),
            Paragraph("PORTFOLIO", style["cellhead"]),
        ], [
            _big(f"{attractiveness:.0f}" if attractiveness is not None else "—", "is the world moving"),
            _big(f"{right_to_win:.0f}" if right_to_win is not None else "—", "can we play, can we win"),
            _big((competition or {}).get("level_label", "—").upper(),
                 f"{(competition or {}).get('counts', {}).get('evidenced', 0)} named in the evidence",
                 colour=COMPETITION_COLOUR.get((competition or {}).get("level", "none"), INK)),
            _big(format_eur((best or {}).get("sam", {}).get("base")) if best else "—",
                 f"{(best or {}).get('confidence', '-')} evidence · per year" if best else "not sized"),
            _big((topic.get("horizon") or "—").upper(),
                 _clip((topic.get("horizon_basis") or "").replace("_", " "), 30)),
            _big(f"L{topic['portfolio_distance']}", f"{topic['signal_count']} signals"),
        ]]
        table = Table(rows, colWidths=[29 * mm] * 6, hAlign="LEFT")
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), INK),
            ("BACKGROUND", (0, 1), (-1, 1), SURFACE),
            ("BOX", (0, 0), (-1, -1), 0.4, RULE),
            ("INNERGRID", (0, 0), (-1, -1), 0.4, RULE),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        header.append(table)
        header.append(Paragraph(
            "Attractiveness and right to win are scored and displayed separately and are never "
            "combined (SC-12). Competition is a fourth quantity, not a discount on either.",
            style["small"]))
        return header

    def _market_size(self, sizes: list[dict[str, Any]]) -> list[Any]:
        style = self.styles
        story: list[Any] = [Paragraph("Market opportunity", style["h2"])]
        if not sizes:
            story.append(Paragraph(
                "No sizing could be computed for this space. The reference data covers the "
                "European business economy; a topic outside it, or one whose technology has no "
                "published adoption series, is left unsized rather than estimated (§4.3.4).",
                style["small"]))
            return story

        head = ["Method", "Total (TAM)", "Serviceable (SAM)", "Obtainable (SOM)", "Confidence"]
        rows = [[Paragraph(h, style["cellhead"]) for h in head]]
        for size in sizes:
            rows.append([
                Paragraph(_text(size["method_label"]), style["cell"]),
                Paragraph(_range(size["tam"]), style["cell"]),
                Paragraph(_range(size["sam"]), style["cell"]),
                Paragraph(_range(size["som"]), style["cell"]),
                Paragraph(_text(size["confidence"]), style["cell"]),
            ])
        table = Table(rows, colWidths=[46 * mm, 34 * mm, 34 * mm, 34 * mm, 18 * mm], hAlign="LEFT")
        table.setStyle(_table_style())
        story.append(table)
        story.append(Paragraph("All figures are annual, in EUR. Ranges compound the uncertainty of "
                               "each factor below; the base case is the middle column of each.",
                               style["small"]))

        for size in sizes:
            story.append(Paragraph(_text(size["method_label"]), style["h3"]))
            factor_rows = [[Paragraph(h, style["cellhead"])
                            for h in ("Factor", "Value", "Basis", "Source", "As of")]]
            for factor in size["factors"]:
                source = factor.get("source") or {}
                origin = " · ".join(
                    part for part in (source.get("publisher"), source.get("dataset"),
                                      source.get("indicator")) if part
                )
                factor_rows.append([
                    Paragraph(_text(factor["label"]), style["cell"]),
                    Paragraph(_text(_factor_value(factor)), style["cell"]),
                    Paragraph(_text(factor["basis"]), style["cell"]),
                    Paragraph(_text(origin or "—"), style["cell"]),
                    Paragraph(_text(str(source.get("period") or "—")), style["cell"]),
                ])
            factors = Table(factor_rows, colWidths=[42 * mm, 32 * mm, 20 * mm, 52 * mm, 20 * mm],
                            hAlign="LEFT")
            factors.setStyle(_table_style())
            story.append(factors)
            if size["caveats"]:
                story.append(Paragraph(
                    "<b>Read this before quoting the number.</b> " +
                    " ".join(_text(c) for c in size["caveats"]), style["small"]))
        return story

    def _diagram(self, description: dict[str, Any] | None) -> list[Any]:
        diagram = (description or {}).get("diagram")
        if not diagram:
            return []
        style = self.styles
        width = A4[0] - 34 * mm
        blocks: list[Any] = [
            Paragraph("The solution, in one picture", style["h2"]),
        ]
        if diagram.get("title"):
            blocks.append(Paragraph(_text(diagram["title"]), style["h3"]))
        blocks.append(SolutionDiagram(diagram, width))
        blocks.append(Spacer(1, 5))
        legend = " &nbsp;&nbsp; ".join(
            f'<font color="{_hex(_swatch(key))}">■</font> {label}'
            for key, label in PROVIDER_LABEL.items()
        )
        blocks.append(Paragraph(legend, style["small"]))
        if diagram.get("caption"):
            blocks.append(Paragraph(_text(diagram["caption"]), style["small"]))
        blocks.append(Paragraph(
            "Boxes marked as Orange assets are validated against the linked business graph; a box "
            "the model claimed for Orange without a matching asset is shown as third party.",
            style["small"]))
        return [KeepTogether(blocks)]

    def _why_hot(self, topic: dict[str, Any]) -> list[Any]:
        style = self.styles
        if not topic.get("why_hot"):
            return []
        story = [Paragraph("Why it is hot now — every claim bound to a dated source", style["h2"])]
        items = []
        for claim in topic["why_hot"][:8]:
            cites = ", ".join(claim.get("signals", [])[:5])
            items.append(ListItem(Paragraph(
                f"{_text(claim['claim'])} <font size=6 color='#777777'>[{_text(cites)}]</font>",
                style["body"]), leftIndent=10))
        story.append(ListFlowable(items, bulletType="bullet", start="•", leftIndent=12))
        return story

    def _delivery(self, topic: dict[str, Any], sections: dict[str, Any],
                  titles: dict[str, str]) -> list[Any]:
        style = self.styles
        story: list[Any] = [Paragraph("What Orange would deliver, and why it can win", style["h2"])]
        for name in ("what_orange_would_deliver", "why_orange_can_win"):
            if name in sections:
                story.append(Paragraph(titles.get(name, name), style["h3"]))
                story.append(Paragraph(_text(sections[name]["text"]), style["body"]))

        links = topic.get("links") or []
        if not links:
            story.append(Paragraph(
                "No Orange asset is linked to this space. That is the finding, not a gap in the "
                "brief: this is white space, and a customer conversation would be a discovery "
                "conversation.", style["small"]))
            return story

        story.append(Paragraph("Named assets behind this — each individually inspectable (LK-08)",
                               style["h3"]))
        # Delivery-bearing links first and in full; published references are
        # capped, because twelve rows of "different use case, same vertical" is
        # a reference list, not a briefing. The count of the rest is kept.
        delivery = [l for l in links if l["node_type"] != "reference"]
        references = [l for l in links if l["node_type"] == "reference"]
        shown = sorted(delivery, key=lambda l: l["link_type"]) + references[:4]
        hidden = max(0, len(references) - 4)
        rows = [[Paragraph(h, style["cellhead"])
                 for h in ("Asset", "Type", "Link", "Why it is linked", "Curator")]]
        for link in shown[:16]:
            rows.append([
                Paragraph(_text(link["label"]), style["cell"]),
                Paragraph(_text(link["node_type"].replace("_", " ")), style["cell"]),
                Paragraph(_text(link["link_type"]), style["cell"]),
                Paragraph(_text(str((link.get("evidence") or {}).get("rule", ""))[:120]), style["cell"]),
                Paragraph(_text(link["confirmed_by"] or "unconfirmed"), style["cell"]),
            ])
        table = Table(rows, colWidths=[44 * mm, 24 * mm, 12 * mm, 60 * mm, 26 * mm], hAlign="LEFT")
        table.setStyle(_table_style())
        story.append(table)
        if hidden:
            story.append(Paragraph(
                f"{hidden} further published reference(s) in this vertical are linked to this topic "
                f"and are listed in the radar.", style["small"]))
        return story

    def _competitor_analysis(self, analysis: dict[str, Any] | None) -> list[Any]:
        """Per-competitor activity and the Orange differentiation angle.

        This is the section a salesperson reads last and uses first, so it is
        laid out per competitor rather than as a table: the differentiation
        paragraph is a thing you say out loud, and a table cell is not.

        Where a competitor's site refused to be read, that is printed. A brief
        that quietly omits four of eight competitors reads as a complete field.
        """
        style = self.styles
        story: list[Any] = [PageBreak(), Paragraph("Competitor analysis", style["h2"])]
        if not analysis or not analysis.get("entries"):
            story.append(Paragraph(
                "No competitor from the register is matched to this space. That is reported as "
                "unverified rather than as an empty field: it may only mean the register has a "
                "gap in this vertical.", style["small"]))
            return story

        coverage = analysis.get("coverage") or {}
        unread = int(coverage.get("blocked", 0)) + int(coverage.get("unread", 0))
        story.append(Paragraph(
            f'{coverage.get("profiled", 0)} of {coverage.get("on_topic", 0)} competitors on this '
            f'space have been read from their own published pages'
            + (f'; {unread} could not be read and are marked below.' if unread else '.'),
            style["small"]))

        if not analysis.get("has_narrative"):
            story.append(Paragraph(
                "<b>The written comparison has not been generated for this space.</b> What follows "
                "is the structural join only — each competitor's own claims, filtered to this "
                "opportunity. Regenerate the brief after writing the comparison to include the "
                "differentiation angle per competitor.", style["small"]))

        narrative = analysis.get("narrative") or {}
        if narrative.get("field"):
            story.append(Paragraph("The shape of the field", style["h3"]))
            story.append(Paragraph(_text(narrative["field"]), style["body"]))

        for entry in analysis["entries"]:
            story.append(Spacer(1, 4 * mm))
            badges = [entry.get("type_label", "")]
            if entry.get("relationship") == "both":
                badges.append("also an Orange partner")
            badges.append(f'{entry.get("basis", "")} presence')
            story.append(Paragraph(
                f'<b>{_text(entry["label"])}</b> '
                f'<font size=7 color="#777777">{_text(" · ".join(b for b in badges if b))}</font>',
                style["body"]))

            if entry.get("profile_status") != "profiled":
                story.append(Paragraph(
                    f'<i>Their published position is unread — {_text(entry.get("profile_reason") or entry.get("profile_status"))}. '
                    f'Nothing below is inferred on their behalf.</i>', style["small"]))
            elif entry.get("positioning"):
                story.append(Paragraph(_text(entry["positioning"]), style["small"]))

            written = entry.get("written") or {}
            activity = (written.get("activity") or {}).get("text")
            if activity:
                story.append(Paragraph(f'<b>Doing here:</b> {_text(activity)}', style["body"]))
            elif entry.get("relevant_claims"):
                claims = "; ".join(c["claim"] for c in entry["relevant_claims"][:3])
                story.append(Paragraph(
                    f'<b>From their own pages:</b> {_text(claims)}', style["small"]))

            if written.get("differentiation"):
                story.append(Paragraph(
                    f'<b><font color="{_hex(ORANGE)}">How Orange differentiates:</font></b> '
                    f'{_text(written["differentiation"])}', style["body"]))
                if written.get("orange_assets"):
                    story.append(Paragraph(
                        f'<font size=7 color="#777777">Anchored on: '
                        f'{_text(" · ".join(written["orange_assets"]))}</font>', style["small"]))
            if written.get("concession"):
                story.append(Paragraph(
                    f'<i>What they do better: {_text(written["concession"])}</i>', style["small"]))
        return story

    def _competition(self, competition: dict[str, Any] | None, sections: dict[str, Any],
                     titles: dict[str, str], topic: dict[str, Any]) -> list[Any]:
        style = self.styles
        story: list[Any] = [Paragraph("Competitive landscape", style["h2"])]
        if not competition:
            story.append(Paragraph("No competitive assessment has been computed for this space.",
                                   style["small"]))
            return story

        level = competition["level"]
        colour = COMPETITION_COLOUR.get(level, INK)
        story.append(Paragraph(
            f'<font color="{_hex(colour)}" size=12><b>{_text(competition["level_label"].upper())}</b></font> '
            f'&nbsp;competitive intensity &nbsp;<font size=7 color="#777777">'
            f'(score {competition["score"]:.1f}; {competition["counts"]["evidenced"]} of '
            f'{competition["counts"]["listed"]} listed players appear in this topic\'s own evidence)</font>',
            style["body"]))
        story.append(Paragraph(_text(competition["meaning"]), style["small"]))

        if "competitive_landscape" in sections:
            story.append(Paragraph(_text(sections["competitive_landscape"]["text"]), style["body"]))
            story += self._citation_line(sections["competitive_landscape"].get("signals"), topic)

        rows = [[Paragraph(h, style["cellhead"])
                 for h in ("Competitor", "Category", "Position here", "Basis", "Evidence")]]
        for entry in competition["competitors"]:
            relationship = {
                "both": "also an Orange partner", "partner": "Orange partner", "competitor": "",
            }.get(entry.get("relationship", "competitor"), "")
            why = entry.get("why", "")
            if relationship:
                why = f"{why} — {relationship}" if why else relationship
            evidence = ", ".join(m["signal_id"] for m in entry.get("mentions", [])[:3]) or "—"
            rows.append([
                Paragraph(_text(entry["label"]), style["cell"]),
                Paragraph(_text(entry.get("type_label", "")), style["cell"]),
                Paragraph(_text(why), style["cell"]),
                Paragraph(_text(entry.get("basis", "")), style["cell"]),
                Paragraph(_text(evidence), style["cell"]),
            ])
        table = Table(rows, colWidths=[34 * mm, 30 * mm, 56 * mm, 20 * mm, 26 * mm], hAlign="LEFT")
        table.setStyle(_table_style())
        story.append(table)
        story.append(Paragraph(
            "<b>evidenced</b> means this topic's own sources name the competitor — the signal ids "
            "are in the last column and are dated and clickable in the radar. <b>structural</b> "
            "means the curated register says they sell this technology into this vertical, which "
            "is true but is not proof they are in this deal. "
            f"Register version {_text(competition['register_version'])}.", style["small"]))
        return story

    def _questions_and_objections(self, description: dict[str, Any] | None) -> list[Any]:
        style = self.styles
        story: list[Any] = []
        questions = (description or {}).get("qualifying_questions") or []
        objections = (description or {}).get("objection_handling") or []
        if questions:
            story.append(Paragraph("Qualifying questions for the first meeting", style["h2"]))
            story.append(ListFlowable(
                [ListItem(Paragraph(_text(q), style["body"]), leftIndent=10) for q in questions],
                bulletType="1", leftIndent=14))
        if objections:
            story.append(Paragraph("Objections you will meet", style["h2"]))
            rows = [[Paragraph(h, style["cellhead"]) for h in ("They will say", "You can answer")]]
            for entry in objections:
                rows.append([
                    Paragraph(_text(entry["objection"]), style["cell"]),
                    Paragraph(_text(entry["response"]), style["cell"]),
                ])
            table = Table(rows, colWidths=[58 * mm, 108 * mm], hAlign="LEFT")
            table.setStyle(_table_style())
            story.append(table)
        return story

    def _actions(self, topic: dict[str, Any], sections: dict[str, Any],
                 titles: dict[str, str]) -> list[Any]:
        style = self.styles
        story: list[Any] = []
        if "risks_and_unknowns" in sections:
            story.append(Paragraph(titles.get("risks_and_unknowns", "Risks and unknowns"), style["h2"]))
            story.append(Paragraph(_text(sections["risks_and_unknowns"]["text"]), style["body"]))

        actions = topic.get("next_actions") or {}
        if not actions:
            return story
        story.append(Paragraph("Next action, by role (FR-17)", style["h2"]))
        rows = [[Paragraph(h, style["cellhead"]) for h in ("Role", "Do this next")]]
        for role_id, action in actions.items():
            role = next((r for r in self.cfg.role_modes_raw["modes"] if r["id"] == role_id), None)
            rows.append([
                Paragraph(_text((role or {}).get("label", role_id)), style["cell"]),
                Paragraph(_text(action), style["cell"]),
            ])
        table = Table(rows, colWidths=[26 * mm, 140 * mm], hAlign="LEFT")
        table.setStyle(_table_style())
        story.append(table)
        return story

    def _evidence_appendix(self, topic: dict[str, Any]) -> list[Any]:
        style = self.styles
        signals = topic.get("signals") or []
        if not signals:
            return []
        story: list[Any] = [PageBreak(), Paragraph("Evidence", style["h2"]),
                            Paragraph(
                                "Every claim in this brief resolves to one of these. Tier 1 is an "
                                "authoritative primary source; tier 4 is vendor-published material, "
                                "discounted in scoring (§4.3.7).", style["small"])]
        rows = [[Paragraph(h, style["cellhead"])
                 for h in ("Signal", "Date", "Publisher", "T", "Title and link")]]
        for signal in signals[:40]:
            title = _text(_clip(signal["title"], 96))
            url = _text(signal.get("url") or "")
            linked = f'<link href="{url}" color="#C24E00">{title}</link>' if url else title
            rows.append([
                Paragraph(_text(signal["id"]), style["cell"]),
                Paragraph(_text(signal["published_at"]), style["cell"]),
                Paragraph(_text(_clip(signal["publisher"], 26)), style["cell"]),
                Paragraph(str(signal["tier"]), style["cell"]),
                Paragraph(linked, style["cell"]),
            ])
        table = Table(rows, colWidths=[30 * mm, 17 * mm, 28 * mm, 7 * mm, 84 * mm], hAlign="LEFT")
        table.setStyle(_table_style())
        story.append(table)
        if len(signals) > 40:
            story.append(Paragraph(
                f"{len(signals) - 40} further sources are attached to this topic and are listed in "
                f"the radar. Truncated here rather than silently dropped.", style["small"]))
        return story

    def _method(self, topic: dict[str, Any], description: dict[str, Any] | None,
                competition: dict[str, Any] | None, sizes: list[dict[str, Any]]) -> list[Any]:
        style = self.styles
        provenance = topic.get("provenance") or {}
        description_provenance = (description or {}).get("provenance") or {}
        stripped = (description or {}).get("stripped") or []

        story = [
            Paragraph("How this brief was made", style["h2"]),
            Paragraph(
                "<b>Computed, not written.</b> Attractiveness, right to win, competitive intensity "
                "and every figure in the market-opportunity section are computed from stored "
                "inputs and can be re-derived (DR-05, NFR-01). No language model produced a number "
                "anywhere in this document (§4.4.4).", style["small"]),
            Paragraph(
                "<b>Written, then checked.</b> The narrative sections and the solution diagram were "
                "generated from this topic's evidence and from the named asset and competitor "
                "lists. Factual sections must cite signal ids attached to this topic; sections that "
                "failed that check, or that contained a generated quantity or an unsupplied "
                "organisation, were removed rather than rewritten.", style["small"]),
        ]
        if stripped:
            story.append(Paragraph(
                "Removed by those checks in this brief: " +
                "; ".join(_text(f"{s['section']} ({s['reason']})") for s in stripped[:6]),
                style["small"]))

        rows = [[Paragraph(h, style["cellhead"]) for h in ("What", "Version", "When")]]
        rows += [
            [Paragraph("Scores — weight set", self.styles["cell"]),
             Paragraph(_text(str(provenance.get("weight_set") or self.cfg.weight_set)), style["cell"]),
             Paragraph(_text(str((topic.get("attractiveness") or {}).get("computed_at", "—"))), style["cell"])],
            [Paragraph("Market sizing — assumptions", style["cell"]),
             Paragraph(_text(sizes[0]["sizing_version"] if sizes else self.cfg.sizing_version), style["cell"]),
             Paragraph(_text(sizes[0]["computed_at"] if sizes else "—"), style["cell"])],
            [Paragraph("Competitor register", style["cell"]),
             Paragraph(_text(str((competition or {}).get("register_version", "—"))), style["cell"]),
             Paragraph(_text(str((competition or {}).get("computed_at", "—"))), style["cell"])],
            [Paragraph("Narrative — prompt / model", style["cell"]),
             Paragraph(_text(f"{description_provenance.get('prompt_version', '—')} / "
                              f"{description_provenance.get('model_version', '—')}"), style["cell"]),
             Paragraph(_text(str((description or {}).get("generated_at", "—"))), style["cell"])],
            [Paragraph("Pipeline", style["cell"]),
             Paragraph(_text(str(provenance.get("pipeline_version") or self.cfg.pipeline_version)), style["cell"]),
             Paragraph(_text(topic["last_refresh"]), style["cell"])],
        ]
        table = Table(rows, colWidths=[52 * mm, 60 * mm, 54 * mm], hAlign="LEFT")
        table.setStyle(_table_style())
        story.append(table)
        story.append(Paragraph(
            f"Generated {dt.datetime.now(dt.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. "
            f"Scores computed under a different weight set are not comparable with these (SC-10), "
            f"and neither are market sizes computed under a different sizing version.",
            style["small"]))
        return story

    # -- helpers -----------------------------------------------------------

    def _citation_line(self, signal_ids: list[str] | None, topic: dict[str, Any]) -> list[Any]:
        if not signal_ids:
            return []
        by_id = {s["id"]: s for s in topic.get("signals") or []}
        parts = []
        for signal_id in signal_ids[:6]:
            signal = by_id.get(signal_id)
            parts.append(
                f"{signal_id} {signal['publisher'][:22]} {signal['published_at']}" if signal else signal_id
            )
        return [Paragraph("Sources: " + _text("; ".join(parts)), self.styles["cite"])]


# ---------------------------------------------------------------------------
# Small helpers and read access
# ---------------------------------------------------------------------------


def _swatch(provider: str) -> colors.Color:
    """Legend colour: the box's fill, unless the fill is too pale to see."""
    fill, _, border = PROVIDER_STYLE[provider]
    red, green, blue = fill.red, fill.green, fill.blue
    return border if (red + green + blue) / 3 > 0.9 else fill


def _hex(colour: colors.Color) -> str:
    """reportlab's hexval() is '0xrrggbb'; its markup parser wants '#rrggbb'."""
    return "#" + colour.hexval()[2:]


def _table_style() -> TableStyle:
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), INK),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SURFACE]),
        ("BOX", (0, 0), (-1, -1), 0.4, RULE),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, RULE),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ])


def _big(value: str, caption: str, colour: colors.Color = INK) -> Paragraph:
    return Paragraph(
        f'<font size=13 color="{_hex(colour)}"><b>{_text(value)}</b></font><br/>'
        f'<font size=6 color="#777777">{_text(caption)}</font>',
        ParagraphStyle("kpi", fontName="Helvetica", fontSize=13, leading=15),
    )


def _range(band: dict[str, float | None]) -> str:
    base = format_eur(band.get("base"))
    low, high = format_eur(band.get("low")), format_eur(band.get("high"))
    if low == high == base:
        return base
    return f"<b>{base}</b><br/><font size=6 color='#777777'>{low} – {high}</font>"


def _factor_value(factor: dict[str, Any]) -> str:
    unit = factor.get("unit", "")
    value = factor.get("value")
    if value is None:
        return "—"
    if "EUR" in unit:
        return f"{format_eur(value)} {unit.replace('EUR ', '')}"
    if unit.startswith("%"):
        return f"{value:.1f} {unit}"
    return f"{value:,.0f} {unit}"


def _text(value: Any) -> str:
    """Make a string safe for the PDF's core fonts, then for its markup parser.

    reportlab's built-in Helvetica is a WinAnsi font, so a character outside it
    — the e-macron in "Mondelez International", say — renders as a black box.
    Substituting a Unicode TTF would fix it and change the whole document's
    typography; decomposing the accent keeps the face and loses only the
    diacritic, which is the smaller loss on a sales brief. Anything that still
    will not encode is dropped rather than boxed.
    """
    text = unicodedata.normalize("NFKD", str(value or ""))
    text = "".join(c for c in text if not unicodedata.combining(c))
    text = text.encode("cp1252", "ignore").decode("cp1252")
    return escape(text)


def _clip(text: str, length: int) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    return text if len(text) <= length else text[: length - 1] + "…"


def _preferred_size(sizes: list[dict[str, Any]]) -> dict[str, Any] | None:
    """The headline size: the bottom-up estimate where one exists.

    §4.3.4 asks for the bottom-up estimate specifically. The procurement figure
    is a floor built from public contracts only, so it belongs beside it rather
    than instead of it — except where no bottom-up estimate exists at all, which
    is exactly the public-sector case where the procurement figure is the better
    evidence anyway.
    """
    for size in sizes:
        if size["method"] == "bottom_up_adoption":
            return size
    return sizes[0] if sizes else None


def brief_for_topic(db: Database, topic_id: str) -> dict[str, Any] | None:
    """Stored brief metadata, with staleness against the topic's version."""
    row = db.query_one("SELECT * FROM topic_briefs WHERE opportunity_id = ?", (topic_id,))
    if row is None:
        return None
    topic = db.query_one("SELECT version FROM opportunity_spaces WHERE id = ?", (topic_id,))
    # A brief goes stale two ways, and only one of them was checked. The topic
    # can move on — and the NARRATIVE can be rewritten underneath it, which is
    # the more likely of the two: someone reads the description, regenerates it,
    # and the PDF they emailed an hour ago now says something the radar does not.
    description = db.query_one(
        "SELECT generated_at FROM topic_descriptions WHERE opportunity_id = ?", (topic_id,)
    )
    description_moved = bool(
        description and row["description_at"] and description["generated_at"] != row["description_at"]
    )
    size = db.query_one(
        "SELECT MAX(computed_at) AS at FROM market_sizes WHERE opportunity_id = ?", (topic_id,)
    )
    sizing_moved = bool(size and size["at"] and row["market_size_at"] and size["at"] != row["market_size_at"])
    path = resolve_brief(row["path"])
    return {
        "topic_id": topic_id,
        "generated_at": row["generated_at"],
        "topic_version": row["topic_version"],
        "filename": row["filename"],
        "bytes": row["bytes"],
        "content_hash": row["content_hash"],
        "exists": path is not None,
        "stale": (bool(topic and topic["version"] != row["topic_version"])
                  or description_moved or sizing_moved or path is None),
        # Which of the three it is, so the warning can say something useful
        # rather than "this is old".
        "stale_reason": (
            "the topic has been refreshed since" if topic and topic["version"] != row["topic_version"]
            else "the written description has been regenerated since" if description_moved
            else "the market size has been recomputed since" if sizing_moved
            else "the PDF file is missing" if path is None else None
        ),
        # INCOMPLETE is not the same as STALE, and conflating them would hide
        # the more actionable of the two. A stale brief was correct when it was
        # made and has been overtaken. An incomplete brief never carried a
        # section that current briefs carry — here, the competitor analysis —
        # so no amount of waiting fixes it and the only remedy is to rebuild.
        "brief_schema": row["brief_schema"],
        "incomplete": row["brief_schema"] != BRIEF_SCHEMA,
        "missing_sections": ([] if row["brief_schema"] == BRIEF_SCHEMA
                             else ["Competitor analysis — what each competitor is doing in this "
                                   "space, and how Orange differentiates against each of them"]),
        "weight_set": row["weight_set"],
        "sizing_version": row["sizing_version"],
        "prompt_version": row["prompt_version"],
        "model_version": row["model_version"],
        "url": f"/api/topics/{topic_id}/brief.pdf",
    }


def brief_path(db: Database, topic_id: str) -> Path | None:
    row = db.query_one("SELECT path FROM topic_briefs WHERE opportunity_id = ?", (topic_id,))
    if row is None:
        return None
    return resolve_brief(row["path"])


def resolve_brief(recorded: str) -> Path | None:
    """The brief file for a recorded path, or None if it is not on this machine.

    The path column records where the brief was written, which is a machine the
    deployment has never seen: briefs are produced by the batch job and shipped
    as files, so on a server the recorded directory does not exist. The filename
    is stable, so fall back to the directory this process actually uses. Without
    this every brief 404s in Azure and the UI reports none were ever generated.
    """
    path = Path(recorded)
    if path.exists():
        return path
    fallback = brief_dir() / path.name
    return fallback if fallback.exists() else None


def brief_dir() -> Path:
    """Where briefs live for this process — see BriefBuilder.output_dir."""
    configured = os.getenv("RADAR_BRIEF_DIR")
    if configured:
        return Path(configured)
    # Anchored the way Config.db_path is, so this and BriefBuilder.output_dir
    # cannot disagree when the process runs from outside the repository root.
    from .config import PROJECT_ROOT
    return (PROJECT_ROOT / os.getenv("RADAR_DB_PATH", "data/radar.db")).parent / "briefs"
